---
title: Support global and component-specific cache configuration
type: feature
description: |
  Cache can be configured for the whole application
  or for a specific components (Hibernate, Shiro).

  ```properties
  # Global cache configuration applied to Hibernate, Shiro and internal components
  # ~~~~~
  # Global cache provider: default/caffeine/redisson
  application.cache.provider = redisson
  # Global cache configuration for specified provider: either on filesystem or resource in classpath
  application.cache.config = redisson.yaml

  # Hibernate-specific cache configuration (takes precedence over global cache configuration)
  # ~~~~~
  #application.cache.hibernate.provider = redisson
  #application.cache.hibernate.config = redisson.yaml

  # Shiro-specific cache configuration (takes precedence over global cache configuration)
  # ~~~~~
  #application.cache.shiro.provider = redisson
  #application.cache.shiro.config = redisson.yaml
  ```
